version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:0.6
    ports:
     - 2181:2181
     - 2888:2888
     - 3888:3888
  kafka:
    image: debezium/kafka:0.6
    ports:
     - 9092:9092
    links:
     - zookeeper
    environment:
     - ZOOKEEPER_CONNECT=zookeeper:2181
     - KAFKA_BROKER_ID=1
     - KAFKA_ZOOKEEPER_CONNECT=zookeeper:32181
     - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:29092
     - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
  postgres:
    image: debezium/example-postgres:0.6
    ports:
     - 5432:5432
    environment:
     - POSTGRES_USER=postgres
     - POSTGRES_PASSWORD=postgres
  connect:
    image: confluentinc/cp-kafka-connect:3.3.0
    ports:
     - 8083:8083
    links:
     - kafka
     - postgres
     - registry
    environment:
     - CONNECT_REST_ADVERTISED_HOST_NAME=connect
     - CONNECT_BOOTSTRAP_SERVERS=kafka:9092
     - CONNECT_GROUP_ID=1
     - CONNECT_CONFIG_STORAGE_TOPIC=my_connect_configs
     - CONNECT_CONFIG_STORAGE_REPLICATION_FACTOR=1
     - CONNECT_OFFSET_STORAGE_TOPIC=my_connect_offsets
     - CONNECT_OFFSET_STORAGE_REPLICATION_FACTOR=1
     - CONNECT_STATUS_STORAGE_TOPIC=my_connect_status
     - CONNECT_STATUS_STORAGE_REPLICATION_FACTOR=1
     # - CONNECT_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_KEY_CONVERTER=io.confluent.connect.avro.AvroConverter
     # - CONNECT_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_VALUE_CONVERTER=io.confluent.connect.avro.AvroConverter
     - CONNECT_INTERNAL_KEY_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_INTERNAL_VALUE_CONVERTER=org.apache.kafka.connect.json.JsonConverter
     - CONNECT_KEY_CONVERTER_SCHEMA_REGISTRY_URL=http://registry:8081
     - CONNECT_VALUE_CONVERTER_SCHEMA_REGISTRY_URL=http://registry:8081
     - CONNECT_LOG4J_ROOT_LOGLEVEL=INFO
  registry:
    image: confluentinc/cp-schema-registry:3.3.0
    ports:
      - 8081:8081
    links:
      - kafka
      - zookeeper
    environment:
      - SCHEMA_REGISTRY_KAFKASTORE_CONNECTION_URL=zookeeper:2181
      - SCHEMA_REGISTRY_HOST_NAME=registry
      - SCHEMA_REGISTRY_LISTENERS=http://registry:8081
  beam:
    image: maven:3.5-jdk-8
    command: mvn compile
    volumes:
      - .:/usr/src/kafka
      - $HOME/.m2:/root/.m2
    working_dir: /usr/src/kafka
    links:
      - kafka
